name: Mac OSX GCC

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: configure
      run: |
        cmake -B build/debug   -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -D ZTD_TEXT_TESTS=ON -D ZTD_TEXT_EXAMPLES=ON -D ZTD_TEXT_GENERATE_SINGLE=ON
        cmake -B build/release -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -D ZTD_TEXT_TESTS=ON -D ZTD_TEXT_EXAMPLES=ON -D ZTD_TEXT_GENERATE_SINGLE=ON

    - name: build
      run: |
        cmake --build build/debug   --config Debug
        cmake --build build/release --config Release

    - name: test
      run: |
        cd build/debug
        ctest --build-config Debug
        cd ../..
        cd build/release
        ctest --build-config Release
        cd ../..
